#ifndef PRINT_UTILS_H
#define PRINT_UTILS_H

#define PREAMBULE "\033["
#define FINAMBULE "m"
#define FORE_RGB(r, g, b) PREAMBULE "38;2;" #r ";" #g ";" #b FINAMBULE
#define FORE_RESET() PREAMBULE "39" FINAMBULE
#define BACK_RGB(r, g, b) PREAMBULE "38;2;" #r ";" #g ";" #b FINAMBULE
#define COLOR_GREY() PREAMBULE "90" FINAMBULE
#define DECORATION_ITALIC() PREAMBULE "3" FINAMBULE
#define DECORATION_ITALIC_OFF() PREAMBULE "23" FINAMBULE

#endif // PRINT_UTILS_H
